### ISSUE TITLE
Proposal for `ct` test metrics

### ISSUE THREAD

**Issue by rimusz** [helm/chart-testing#124]
Produce `ct` test metrics file for each tested chart.
1) Main use case would be using `ct` with https://github.com/helm/chart-releaser.
2) Then helm repos wanted to be part of https://hub.helm.sh can be checked that charts there are tested with `ct`

**Comment by rimusz** [comment]
cc @scottrigby

**Comment by jlegrone** [comment]
@rimusz can you expand on point 1? What metrics would be exposed, and how? Would this file be published as part of the chart?

**Comment by rimusz** [comment]
sorry had put the wrong url in 1).
The idea came up from Charts maintainers call about the test metrics.

1) We could have test metrics per chart, which could be placed in the charts git repo folder, I think that would make easier when having the one test metrics for the repo.
We haven't discussed what should be stored in the test metrics file, but at least something indicating it had passed `ct` tests.
2) For the start not enforcing of `ct` use for chart testing, we could show in https://hub.helm.sh some icon/wording that it was tested with `ct`.
In future when we agree to enforce `ct` use, only charts with `ct` successful  test metrics can be accepted in the https://hub.helm.sh.
The main idea is to have high quality charts in https://hub.helm.sh

**Comment by scottrigby** [comment]
Relates to https://github.com/helm/hub/issues/42
