### ISSUE TITLE
Proposal: Enable full set of checks for charts not in a parent directory

### ISSUE THREAD

**Issue by jlegrone** [helm/chart-testing#125]
## The Problem

Right now the `--charts` flag disables chart version validation and change detection. From the usage text:

```
Specific charts to test. Disables changed charts detection and
version increment checking. May be specified multiple times
or separate values with commas
```

This flag is also currently the only way to test charts that are not part of a chart "parent directory", which is a known use case (see #101 or [goharbor/harbor-helm](https://github.com/goharbor/harbor-helm)).

## Proposal

1. Add a new flag for testing specific charts that does include change detection

or

2. Make a breaking change to _not_ disable change detection when `--charts` is used, but support 
         the old behavior with `--charts ./somechart --all`.

Also remove the default value for `--chart-dirs`, since there doesn't seem to be a great way to override string slice args to be empty (see https://github.com/helm/chart-testing/pull/104#issuecomment-469603952).

**Comment by jlegrone** [comment]
I'm thinking this might also make it easier to support using `ct` as a helm plugin at some point.

**Comment by lsowen** [comment]
@jlegrone I was just dealing with this.  Do you know this historical reasons behind why change detection is disabled when using `--charts`?

**Comment by jlegrone** [comment]
@lsowen I'm not 100% on this but I think the use case was for singling out specific charts for testing in the large community charts repo. That can still be accomplished after this proposed change by configuring `ct` to not discover charts from parent directories, eg: `--charts stable/redis` for a specific chart, or `--chart-dirs stable,incubator` for all charts.

**Comment by unguiculus** [comment]
@jlegrone Not sure what you mean with old behavior with `--charts ./somechart --all`.

It doesn't make sense to use these flags together. `--charts` tests specific charts while `--all` tests all charts. In these cases, no Git logic is involved, i. e. there is not change detection. These flags are meant to test charts unconditionally. Thus, there can be no version bump checking.
