### ISSUE TITLE
Decide on / request Slack channel for chart-testing

### ISSUE THREAD

**Issue by scottrigby** [helm/chart-testing#131]

**Comment by jlegrone** [comment]
Some reasons this would be nice

1. Open up development discussion that has historically been in slack PMs to the community
1. Provide an avenue for user support beyond github issues
1. Existing helm-related channels have enough traffic that it would be difficult for chart-testing maintainers to moderate/be responsive to discussion

**Comment by scottrigby** [comment]
In Today's Helm Dev meeting, @bacongobbler raised this question I asked about in keybase. @michelleN [commented](https://docs.google.com/a/r6by.com/document/d/1d-6xJEx0C78csIYSPKJzRPeWaHG_8W1Hjl72OJggwdc/edit?disco=AAAAC5Zvo7g) the k8s community now has [slack channel guidelines](https://github.com/kubernetes/community/blob/master/communication/slack-guidelines.md#requesting-a-channel) we can follow for new channels, rather than just pinging people like we used to do 👏🙌  

Following the guidelines, and issue template, I opened https://github.com/kubernetes/community/issues/3573

PS, the _GitHub Username_ and _Slack Username_ section of that issue template are
> the Channel/Bot/Token/Webhook owner or primary contact

I don't think it really matters which of us they list internally. I'll keep this issue updated when there's more progress 😄

**Comment by scottrigby** [comment]
Anyone else want to weigh in on this issue? kubernetes/community#3573

I'm thinking #helm-dev isn't the best place for dev discussion about helm/chart-testing (or other helm projects like chart-releaser, etc). I'm thinking that channel is best to focus on development of helm/helm. I'm assuming no one disagrees or we would have already suggested just using that channel for all helm projects?

**Comment by rimusz** [comment]
#helm-dev is for sure not the place to discuss charts testing development

**Comment by scottrigby** [comment]
🙌 https://github.com/kubernetes/community/pull/3593
