### ISSUE TITLE
panic error when exeu ct lint-and-install

### ISSUE THREAD

**Issue by h00130372** [helm/chart-testing#136]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
I use chart-testing v2.2.0 docker： quay.io/helmpack/chart-testing:v2.2.0 to test ct lint and install:
docker exec --interactive ctd "$@" ct lint-and-install --charts stable/mysql,stable/postgresql,stable/etcd-operator,stable/coredns --namespace kube-system

then I get the error:

$HELM_HOME has been configured at /root/.helm.
Not installing Tiller due to 'client-only' flag having been set
Happy Helming!
"incubator" has been added to your repositories
No requirements found in stable/mysql/charts.
Linting chart 'stable/mysql'
Validating /workdir/stable/mysql/Chart.yaml...
Validation success! 👍
Validating maintainers...
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/helm/chart-testing/pkg/tool.parseOutGitRepoDomain(0xc0000142dc, 0x3, 0xc00004e400, 0xc000010330)
	/go/src/github.com/helm/chart-testing/pkg/tool/account.go:44 +0x6f
github.com/helm/chart-testing/pkg/tool.AccountValidator.Validate(0xc0000142dc, 0x3, 0xc000014170, 0x9, 0x0, 0x0)
	/go/src/github.com/helm/chart-testing/pkg/tool/account.go:29 +0x4d
github.com/helm/chart-testing/pkg/chart.(*Testing).ValidateMaintainers(0xc000084180, 0xc0000da4c0, 0xc, 0xc00007f860, 0x15)
	/go/src/github.com/helm/chart-testing/pkg/chart/chart.go:565 +0x202
github.com/helm/chart-testing/pkg/chart.(*Testing).LintChart(0xc000084180, 0xc0000da4c0, 0xc, 0x0, 0x0, 0x0, 0x3, 0x0, 0x0, 0xc000178720)
	/go/src/github.com/helm/chart-testing/pkg/chart/chart.go:312 +0x534
github.com/helm/chart-testing/pkg/chart.(*Testing).LintAndInstallChart(0xc000084180, 0xc0000da4c0, 0xc, 0x0, 0x0, 0x0, 0xc0000da4c0, 0xc, 0x0, 0x0)
	/go/src/github.com/helm/chart-testing/pkg/chart/chart.go:389 +0x67
github.com/helm/chart-testing/pkg/chart.(*Testing).LintAndInstallChart-fm(0xc0000da4c0, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/helm/chart-testing/pkg/chart/chart.go:257 +0x63
github.com/helm/chart-testing/pkg/chart.(*Testing).processCharts(0xc000084180, 0xc0000e7828, 0xc000097832, 0x922d80, 0xc3c4e0, 0x922da0, 0xc3c4e0)
	/go/src/github.com/helm/chart-testing/pkg/chart/chart.go:232 +0x6df
github.com/helm/chart-testing/pkg/chart.(*Testing).LintAndInstallCharts(0xc000084180, 0x3, 0xc000097298, 0x6, 0x0, 0x0)
	/go/src/github.com/helm/chart-testing/pkg/chart/chart.go:257 +0x4e
github.com/helm/chart-testing/app/cmd.lintAndInstall(0xc00014d180, 0xc0000aae00, 0x0, 0x4)
	/go/src/github.com/helm/chart-testing/app/cmd/lintAndInstall.go:53 +0x20c
github.com/helm/chart-testing/vendor/github.com/spf13/cobra.(*Command).execute(0xc00014d180, 0xc0000aadc0, 0x4, 0x4, 0xc00014d180, 0xc0000aadc0)
	/go/src/github.com/helm/chart-testing/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/helm/chart-testing/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00014ca00, 0xc000098120, 0xc00014d680, 0xc00014d400)
	/go/src/github.com/helm/chart-testing/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/helm/chart-testing/vendor/github.com/spf13/cobra.(*Command).Execute(0xc00014ca00, 0x405690, 0xc000076058)
	/go/src/github.com/helm/chart-testing/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/helm/chart-testing/app/cmd.Execute()
	/go/src/github.com/helm/chart-testing/app/cmd/root.go:57 +0x27
main.main()
	/go/src/github.com/helm/chart-testing/app/main.go:22 +0x20
+ docker container rm --force ctd

**Version of Helm and Kubernetes**:

helm version: v2.12.2 (including in chart-testing image)
kubectl version: v1.14.0 and v1.12.7, both failed with the above error msg
ct version: v2.2.0

**Comment by h00130372** [comment]
If I pass the arg ValidateMaintainers: false then the lint is ok? So what's the problem?

**Comment by jlegrone** [comment]
@h00130372 it looks like this is caused by this line in particular (which we should fix):

https://github.com/helm/chart-testing/blob/c97c7907c32fd04f6bc486d7537a22454b5c642d/pkg/tool/account.go#L44

I'm curious, what do you get when you execute `git ls-remote --get-url` in the `ct` container?

**Comment by jlegrone** [comment]
@h00130372 the panic should be fixed on `master`. When you get a chance please let us know what the output of `git ls-remote --get-url` yields!
