### ISSUE TITLE
Proposal: helm 2.13 instead of 2.12 in docker image

### ISSUE THREAD

**Issue by vv-p** [helm/chart-testing#140]
**What happened**:
helm in the ct docker image knows nothing about --atomic option because it was added in the 2.13.0 helm release

**What you expected to happen**:
latest helm version in the ct docker image

**How to reproduce it** (as minimally and precisely as possible):
```
docker run -ti --rm quay.io/helmpack/chart-testing:v2.3.0 sh
helm upgrade release chart --install --wait --atomic --timeout=300

Error: unknown flag: --atomic
```

**Comment by cpanato** [comment]
thanks @vv-p i will update that
