### ISSUE TITLE
Validate maintainers in GitLab runners

### ISSUE THREAD

**Issue by alvgarvilla** [helm/chart-testing#156]
**BUG REPORT**

**Version of Helm and Kubernetes**:
Helm v2.12.3
Kubernetes v1.11.7

**What happened**:

For validating the maintainers it sends a HEAD request to the URL built like: _repoUrl/maintainerName_. 

_repoUrl_ is obtained  through the following command:

`git ls-remote --get-url origin`

In most of the cases, if you run it the output for GitLab would be something like:

`https://gitlab.com/my-nice-group/MyNiceProject.git`

Which matches perfectly with the regex expression defined in https://github.com/helm/chart-testing/blob/master/pkg/tool/account.go#L27

But if you run that command in a GitLab runner, the output would be:

`https://gitlab-ci-token:[MASKED]@gitlab.com/my-nice-group/MyNiceProject.git`

So the validation will always fail with the following error:

`Error validating maintainers: Head https://gitlab-ci-token/garcal01: dial tcp: lookup gitlab-ci-token on 192.168.0.10:53: server misbehaving
`

**What you expected to happen**:
regex expression also matches GitLab runner output

**How to reproduce it** (as minimally and precisely as possible):
Use helm/chart-testing tool in a GitLab runner validating maintainers

**Comment by unguiculus** [comment]
Thanks for reporting this. Would you mind submitting a PR to fix this?
