### ISSUE TITLE
Is there any plan for helm v3?

### ISSUE THREAD

**Issue by Somefive** [helm/chart-testing#158]
**Is this a request for help?**: No.
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST.

**Anything else we need to know**:
I know it might be a bit early to talk about helm v3 support but since helm v3's api changes a lot which makes chart-testing fail in several ways, it would be great to know if there is a plan for helm v3 support. Thanks!

**Comment by jlegrone** [comment]
Yes, helm 3 will be supported. We're still working out some of the `helm test` API changes which will need to be finalized first.

**Comment by scottrigby** [comment]
We now have a [v3.0.0-beta.1](https://github.com/helm/chart-testing/releases/tag/v3.0.0-beta.1) release. Please test and report issues 😄
