### ISSUE TITLE
Support custom chart processors via exec-based plugin system

### ISSUE THREAD

**Issue by jlegrone** [helm/chart-testing#163]
As a way to support custom linting and other chart validation use cases, I propose that we allow users to specify custom chart processors that do not require compilation into `ct`.

The implementation might look something like this:

```go
type ChartProcessor interface {
	ProcessChart(*Chart) TestResult
}

type ExecManifestProcessor struct {
	Command []string
}

// ProcessChart renders a chart (once for each values file) and executes Command
// passing the rendered manifests as input via Stdin.
//
// Runtime complexity is O(n) where n is the number of CI values files.
func (e ExecManifestProcessor) ProcessChart(chart *Chart) TestResult {
	...
}
```

Users would then be able to specify custom processors, eg. an [OPA based linter](https://www.openpolicyagent.org/), a shell script, etc.

There are two sorts of plugins which could be supported:

1. Those which can accept a set of pre-rendered yaml manifests via Stdin
    - `kubectl apply --server-dry-run`
    - [kubeval](https://github.com/instrumenta/kubeval)
    - [conftest](https://github.com/instrumenta/conftest)
2. Those which accept a helm chart path as input
    - [helm-opa plugin](https://github.com/eicnix/helm-opa)
    - [helm lint](https://github.com/helm/helm/blob/55193089e67207363e6f448054113b5a36649d74/docs/helm/helm_lint.md) (this is already natively supported by `ct` but would easily be refactored as a plugin)

The `ct` configuration should distinguish between these two types, and more may be added in the future (eg. processors which accept JSON manifests as input).

### Other Considerations
1. We could just build support for new processors directly into `ct`. This would be a better experience for end users, but is not scalable. Custom processors may still "graduate" to directly supported default plugins like `helm lint`.
1. We could explicitly support using `ct` as a go library and allow others to build their own CLIs that integrate custom processors. This might lead to fragmentation, and isn't a satisfactory solution for those who have simple needs.

**Comment by cornfeedhobo** [comment]
@jlegrone @unguiculus @scottrigby Can we revisit this topic?

@griffin Why did you close #165?
