### ISSUE TITLE
ct lint passed a chart which failed in helm lint verification

### ISSUE THREAD

**Issue by zzxwill** [helm/chart-testing#169]
**Is this a request for help?**:
No.
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
/charts/submitted/redis-operator # helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp 127.0.0.1:8080: connect: connection refused

Not installed in Kubernetes.

/charts/submitted/redis-operator # helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp 127.0.0.1:8080: connect: connection refused
/charts/submitted/redis-operator # kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
/charts/submitted/redis-operator # ct version
Version:	 v2.3.3
Git commit:	 e731d947fbcdb6c8b79f475adc6fefb6f998fdff
Date:		 2019-08-06T12:48:25Z
License:	 Apache 2.0

**What happened**:

I  run `ct lint` and it passed.
```
/charts/submitted/redis-operator # ct lint .
Linting charts...
------------------------------------------------------------------------------------------------------------------------
 Configuration
------------------------------------------------------------------------------------------------------------------------
Remote: origin
TargetBranch: master
BuildId:
LintConf: /etc/ct/lintconf.yaml
ChartYamlSchema: /etc/ct/chart_schema.yaml
ValidateMaintainers: true
ValidateChartSchema: true
ValidateYaml: true
CheckVersionIncrement: true
ProcessAllCharts: false
Charts: []
ChartRepos: []
ChartDirs: [charts]
ExcludedCharts: []
HelmExtraArgs:
HelmRepoExtraArgs: []
Debug: false
Upgrade: false
SkipMissingValues: false
Namespace:
ReleaseLabel:
------------------------------------------------------------------------------------------------------------------------
All charts linted successfully
------------------------------------------------------------------------------------------------------------------------
No chart changes detected.
------------------------------------------------------------------------------------------------------------------------
```

**What you expected to happen**:

Apparently it should fail as the `name` of the Chart is required, here is the result of `helm lint .`
```
/charts/submitted/redis-operator # helm lint .
==> Linting .
[ERROR] Chart.yaml: name is required
[ERROR] Chart.yaml: directory name (redis-operator) and chart name () must be the same
[ERROR] templates/: invalid chart (Chart.yaml): name must not be empty

Error: 1 chart(s) linted, 1 chart(s) failed
```

**How to reproduce it** (as minimally and precisely as possible):

- Build from source to by `./build.sh -r`
- Run the image with `docker run -itd`
- Go into the docker with `docker exec -it xxx sh`
- Do the verification.

**Anything else we need to know**:

**Comment by unguiculus** [comment]
The tool reported `No chart changes detected` so it didn't do anything.

**Comment by zzxwill** [comment]
But it should report the issue similar to that of the below.
```
/charts/submitted/redis-operator # helm lint .
==> Linting .
[ERROR] Chart.yaml: name is required
[ERROR] Chart.yaml: directory name (redis-operator) and chart name () must be the same
[ERROR] templates/: invalid chart (Chart.yaml): name must not be empty

Error: 1 chart(s) linted, 1 chart(s) failed
```

**Comment by marco2704** [comment]
@zzxwill You are passing `.` as argument to `helm lint`, which is fine since its usage is `helm lint PATH [flags]`. But with the `ct lint` is different, since its usage is: `ct lint [flags]`, it does not accept arguments only flags. The `charts` directory is where is going to look for the charts, if `--chart-dirs` is not set.

Nevertheless I'm facing same bug, even setting the `--all` flag.
