### ISSUE TITLE
How to use ct list-changed to get non-empty results?

### ISSUE THREAD

**Issue by ygqygq2** [helm/chart-testing#173]
When I use `ct list-changed`, the result is nil. How to use ct list-changed to get non-empty results?
![image](https://user-images.githubusercontent.com/17672440/65122852-8665b100-da24-11e9-812f-382f9f85902b.png)

**Comment by jeff-knurek** [comment]
@ygqygq2 More info is needed to help in this case.
The simple answer is that you need to make a change in the chart, and do a git commit for the change to be detected. 
The longer answer depends on your folder structure, and naming schema of your working dir.
