### ISSUE TITLE
Add bash to quay.io/helmpack/chart-testing image

### ISSUE THREAD

**Issue by alex-yust** [helm/chart-testing#174]
**FEATURE REQUEST**

Add bash package to quay.io/helmpack/chart-testing image, 
Sadly, but Azure Pipelines is only capable to run scripts on a Linux system via bash. It specifically checks presence of bash before running any shell command, so you can't even install bash using 'sudo apt install bash' 8-( 

**Version of Helm and Kubernetes**:
quay.io/helmpack/chart-testing:v2.3.3

**Comment by unguiculus** [comment]
For Azure Pipelines you need more than just Bash. 

See https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops#non-glibc-based-containers

We're not going to install all these dependencies. You should create your own image in this case.
