### ISSUE TITLE
 Proposal: update docker image on quay.io

### ISSUE THREAD

**Issue by vsliouniaev** [helm/chart-testing#179]
We have helm 2.14.1 in Dockerfile and 2.13.1 in the latest docker image in quay.io.

Helm 2.13.1 has some bugs that are affecting the github.com/helm/charts tests. For example, this issue: https://github.com/helm/charts/issues/9241 is affecting builds.

Could you please update the image to use at least the latest 2.14.x version of Helm?

**Comment by jeff-knurek** [comment]
👍 and also provide the `v2.15.2` image
