### ISSUE TITLE
Check for mutating matchLabels in apps/v1

### ISSUE THREAD

**Issue by mattfarina** [helm/chart-testing#19]
`matchLabels` cannot change in `apps/v1` (e.g., StatefulSet). That means things like the `chart` label cannot change when the version increments. This is no longer allowed.

A way to catch an error on the chart or other common labels would be useful.

**Comment by desaintmartin** [comment]
Actually, even apps/v1beta2 (and extension/v1beta2?) are affected.

See https://github.com/helm/charts/issues/7680 for reference issue.

**Comment by jlegrone** [comment]
Would it be a good idea to test that an existing install can be upgraded successfully? We could catch this and some additional classes of bugs related to upgrades, like missing checksums for configmaps/secrets.

A static analysis of templates would provide much more actionable feedback, however.

**Comment by scottrigby** [comment]
@jlegrone see #25
