### ISSUE TITLE
Use of --wait by default breaks some charts

### ISSUE THREAD

**Issue by rainest** [helm/chart-testing#202]
**Is this a request for help?**:
Yes.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm:
```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```
Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
chart-testing:  v2.4.0, using the [quay.io Docker image](https://quay.io/repository/helmpack/chart-testing?tag=latest&tab=tags)

Basic testing with Helm3 and review of the chart-testing 3.0.0 beta code suggests the same issue should occur with them.

**What happened**:
A chart that installs successfully with `helm install -f example.yaml /path/to/chart` fails to pass `ct install`, as a critical post-install hook is not created, and some pods never come online as a result.

**What you expected to happen**:
Given the same options `ct install` results in the same installation success/failure as `helm install`, and creates the post-install hook at the same time.

**How to reproduce it** (as minimally and precisely as possible):
Generally speaking, install a chart with a post-install hook job, where one or more pods depend on that job completing successfully. Use `helm install` normally, and do not pass `--wait`. Attempt the same with `ct install`, without adding `--helm-extra-args "--wait"`.

For a more concrete example, see https://github.com/Kong/charts/pull/36 and its associated branch/CI result. That branch installs normally with Helm itself, but fails due to lack of readiness when given to chart-testing.

**Anything else we need to know**:
`--wait` is hard-coded into the Helm invocations used in [2.4](https://github.com/helm/chart-testing/blob/v2.4.0/pkg/tool/helm.go#L62-L63) and [3.0](https://github.com/helm/chart-testing/blob/v3.0.0-beta.1/pkg/tool/helm.go#L58-L59), and has been present since the initial Go conversion. It was present in the [initial shell script import/split from "charts"](https://github.com/helm/chart-testing/blob/96d2ce7c0ebb573fc119175789be5cb4acfe72b9/lib/chartlib.sh#L286) but not in what appears to be the [equivalent script in "charts"](https://github.com/helm/charts/blob/efa000e429d2169c1c7142c68b8da678898100ff/test/changed.sh#L104) before that split.

After initial review, it's not clear to me whether it's possible to handle this case by simply removing the flag without making changes to Helm also. At least for Helm3, `--wait` appears to pull double duty, handling both "fail the release if pods do not become ready" and "require pods become ready before creating post-install resources": https://github.com/helm/helm/blob/v3.0.3/pkg/action/install.go#L282-L293

To remove that and handle this without changes to Helm, I'd expect that chart-testing would need some other means of checking pod readiness afterwards.

**Comment by jlegrone** [comment]
I'm a little confused. Have we identified charts that will never work with the `helm upgrade --install --wait`?

If not, is `chart-testing` failing to install and upgrade charts using the same workflows we would expect real users to go through, or is there a bug causing `post-install` hooks to not be executed?

**Comment by thomastaylor312** [comment]
You are correct here. `--wait` assumes your pods are ready before continuing to post install. The reason being is that it is waiting for the install/upgrade step and not for the post-install (which is the next step). I don't understand a lot of the internals with chart testing, but what is the reason a `post-*` hook is used for dependent pods rather than a `pre-*` hook? 

Like I said, I don't have enough context to give an exact suggestion, but if there is a chart designed in such a way that dependencies are taken care of with a `post-*` hook, `--wait` might not be the right thing there

**Comment by rainest** [comment]
In our case, the installed deployments are Postgres (via a subchart) and Kong. The `post-install` hook is a job that handles initialization of the Postgres schema, and the Kong deployment blocks startup until that initialization is complete.

We currently spawn this job as part of the installed resources (no hook), but users must then delete it manually before upgrades to avoid immutability conflicts. [Job TTLs](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#ttl-mechanism-for-finished-jobs) would work around this, but aren't really viable for us to use until they're out of alpha.

`pre-install` doesn't work here because the job fails if Postgres is not yet up, and as far as I know there isn't a way to spawn a subchart in `pre-install` (and we furthermore want its deployment managed as part of the release).

Assuming there's no other way to work around this in the chart itself, I can think of three options on the Helm end that allow chart-testing to still confirm the installation's success while still creating this dependency immediately after resource creation:
* Define a new hook type (`post-create`?) that executes [after create, but before wait](https://github.com/helm/helm/blob/v3.0.3/pkg/action/install.go#L281).
* Add an additional flag that defers the `KubeClient.Wait()` call until after creating `post-install` hooks.
* Add a new command or modify an existing one to provide a means for chart-testing to confirm the success of a release after it runs `helm install` without `--wait`. 

While I like the new/modified command option most, https://github.com/helm/helm/issues/5952 suggests it's probably not viable. Failing that, the new hook type seems most appealing. Does it seem reasonable to add one for this, or is this too narrow a use case to justify it?

**Comment by unguiculus** [comment]
chart-testing just calls Helm. We need to use `--wait`. Otherwise we'd have to implement custom logic here which IMO we should not do.

**Comment by rainest** [comment]
Lack of a viable CLI tool to determine release status presumably means there's no good way to handle this in chart-testing. Closing this, will open a Helm/helm proposal depending on whether we can find some other means of handling this on our end.

**Comment by thesuperzapper** [comment]
I resolved this issue for the [airflow helm chart](https://github.com/airflow-helm/charts/tree/main/charts/airflow) by creating a value called `helmWait`, which just removes the `helm.sh/hook` annotations if enabled, (but only for the hooks which actually need to run BEFORE other Pods are in a Ready state).

I then set `helmWait` to `true` in my `ci/XXX.values.yaml` files, so that chart-testing picks it up.
