### ISSUE TITLE
Load test dependencies from external file

### ISSUE THREAD

**Issue by krylovsk** [helm/chart-testing#211]
**FEATURE REQUEST**
For integration testing it is often required to install additional dependencies before executing the tests. Today this requires pre-provisioning a namespace by installing and configuring all dependencies, executing tests in that namespaces (`ct install --namespace <configured-namespace>`), and cleaning it up afterwards

It would be great to do all of that with `ct` directly by installing dependencies before running the tests e.g. from `ci/ci-requirements.yaml`. Then the dependencies could be configured by passing the values to them from `ci/*-values.yaml`.

An alternative could be setting up such test dependencies in the `Chart.yaml` directly and disabling them using `tags` or `conditions`. However, this brings testing configuration into the helm chart itself and with `helm package` all testing dependencies will be packaged into the chart.

**Comment by unguiculus** [comment]
chart-testing is meant to test individual charts in isolation. Such a feature would be out of scope. I'd rather keep the tool focused.

**Comment by krylovsk** [comment]
We eventually went the path of configuring dependencies in `Chart.yaml` as dev dependencies and a condition disabling them by default. Having them packaged in final `helm package` is rather an artefact for us, but it also makes our charts self-contained.

Will close the issue as no one else expressed interest and we've been fine with this approach so far. For anyone running into the same issue, below is an example illustrating the approach we went with:

`Chart.yaml` defining the dev dependency:

```yaml
# ... (chart definition)

dependencies:
  - name: dep1
    version: ~0.1.0
    repository: file://../dep1  # for dependency in the same repo
    condition: dep1.enabled
  - name: dep2
    version: ~3.2.0
    repository: https://kubernetes-charts.storage.googleapis.com/  # for external dependency
    condition: dep2.enabled
```

`values.yaml` disabling the dev dependency:

```yaml
# ...  (default values for your chart)
dep1:
  enabled: false

dep2:
  enabled: false
```
