### ISSUE TITLE
'Directory is not a valid chart directory'

### ISSUE THREAD

**Issue by alex-hempel** [helm/chart-testing#226]
**Is this a request for help?**: Yes

**Version of Helm and Kubernetes**:

ct version v3.0.0-rc.1 (Docker image)

**What happened**:
I am trying to run `ct lint` against my local copy of the git repo, comparing against the charts hosted in my private helm repo.

Using the Docker image, I run the following command line:

`docker run -v `pwd`:/`pwd` -w `pwd` quay.io/helmpack/chart-testing:latest ct lint --chart-dirs `pwd` --chart-repos <repo-name>=https://<repo-url> --helm-repo-extra-args "<repo-name>=--username <user> --password <password>"`

I have changes in my local copy that aren't on the remote. For each changed chart, the output is 'Directory '<chart-dir>' is not a valid chart directory. Skipping...`

**What you expected to happen**:
Either to see linting output, or to get told why the directory is not considered valid.

What can I look at to understand why ct lint thinks the chart directory is not valid?

**Comment by bonifaido** [comment]
This can happen when the lint configuration YAML is in the same directory as your charts.

**Comment by shreben** [comment]
Hello @alex-hempel 
have you managed to resolve the issue?

**Comment by jdomag** [comment]
having the same issue..

**Comment by arthurk** [comment]
Same issues with 3.7.0 running on the [linkerd-viz chart](https://github.com/linkerd/linkerd2/tree/main/viz/charts/linkerd-viz)

```
Linting charts...
Directory 'helm-charts/linkerd/linkerd-viz' is not a valid chart directory. Skipping...
------------------------------------------------------------------------------------------------------------------------
No chart changes detected.
------------------------------------------------------------------------------------------------------------------------
All charts linted successfully
```

Would be great if ct can show a more detailed error message on why the chart dir is not valid

**Comment by brunopadz** [comment]
I was experiencing the same problem. I solved by moving my chart to a directory called `chart`.

```
./chart/my-chart/
```

**Comment by dsever** [comment]
Really there is no solution for it?  I'm facing the same as chart is in `deployment/kubernetes`
