### ISSUE TITLE
hardcoded 180s for kubectl delete namespace is causing timeouts

### ISSUE THREAD

**Issue by nvtkaszpir** [helm/chart-testing#227]
**Is this a request for help?**:

No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report, minor.

**Version of Helm and Kubernetes**:
helm version
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

kubectl version
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.24", GitCommit:"39e41a8d6b7221b901a95d3af358dea6994b4a40", GitTreeState:"clean", BuildDate:"2020-02-29T01:24:35Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```
ct version
```
 docker run quay.io/helmpack/chart-testing ct version
Version:	 v3.0.0-rc.1
Git commit:	 16513fad69626142ccd84e9171397df317806cb0
Date:		 2020-04-03T03:54:12Z
License:	 Apache 2.0
```

**What happened**:
ct gets a timeout when deleting namespace used for chart testing, it takes over 180s.

**What you expected to happen**:
Increase timeout

**How to reproduce it** (as minimally and precisely as possible):
just run any complex chart with dependencies that makes persistent volumes and clustering.

**Anything else we need to know**:

https://github.com/helm/chart-testing/blob/master/pkg/tool/kubectl.go#L36 has hardcoded 180s timeout.
Would be nice to be able to control it, some charts are pretty slow and complex and even deleting namespaces takes some time, espacially because of finalizers.

**Comment by mattfarina** [comment]
Thanks for filing the issue. Do you have an example chart we could use to validate the work against?

I think the ability to pass in a configurable timeout would solve this issue.

**Comment by nvtkaszpir** [comment]
You can try with elasticsearch https://github.com/helm/charts/tree/master/stable/elasticsearch  - it has quite complex setup with persistent volumes and pod termination grace period set to 1 hour :)

**Comment by itewk** [comment]
i ran into this to when testing chart running on kind cluster running in github actions. i think its just due to kind on github actions being sloooow. when i run locally its not a problem.
