### ISSUE TITLE
Practical how to guide

### ISSUE THREAD

**Issue by mattfarina** [helm/chart-testing#241]
The current documentation is targeted at commands of the application rather than the experience of using it and accomplishing tasks. If I were to point someone here and suggest they start using it they would likely not know where to begin or what to do.

A way to make it easier to onboard people is to provide practical how-to documentation.

This is an issue to record adding such documentation.

**Comment by nvtkaszpir** [comment]
Do you need a typical 'step-by-step' user guide?

**Comment by davidkarlsen** [comment]
I think this is mostly covered by the demo repo: https://github.com/helm/charts-repo-actions-demo ?

**Comment by nvtkaszpir** [comment]
@davidkarlsen so it looks like that additional repo should be mentioned in the docs/readme of this repo.
