### ISSUE TITLE
Document feature:  'ci' subfolder of the chart directory matching the pattern '*-values.yaml'

### ISSUE THREAD

**Issue by max-rocket-internet** [helm/chart-testing#257]
It's [here](https://github.com/helm/chart-testing/blob/93b10e8e55baea22e57f52ad653de2d6bcc199c5/pkg/chart/chart.go#L176) but not mentioned in the README 🙂

**Comment by davidkarlsen** [comment]
It's documented at https://github.com/helm/chart-testing/blob/master/doc/ct_install.md

**Comment by max-rocket-internet** [comment]
OK, my bad!

Do you think this feature warrants a mention in the main README? I'd be happy to make a PR 🙂
