### ISSUE TITLE
[FEATURE REQUEST] Possible way to bypass base64 conversion issue for Kubernetes secrets created using helm-charts

### ISSUE THREAD

**Issue by ankitsrao** [helm/chart-testing#264]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm Version 3.3.0
Kubernetes Version 1.18

**What happened**:
So, when I completed the CT setup using git workflows, I get an error saying "Illegal base64 data", in the chart-testing phase.
This is because, the helm chart that I have, creates 2 kubernetes secrets (keys) which are expected in the base 64 format.
But while I have published my chart, I have added placehoders in the values.yaml file for the secrets (eg: apisecret: <apisecret>), which I input from the user during the chart installation, in base64 format as a security best practice.

But the ct tool, is picking up the placeholders as keys and throwing the above error.

**What you expected to happen**:
I would request you to provide any way to tackle this behavior.

One solution is that I can use the "| b64enc" for conversion in the chart itself, but then as I expect the user of the helm chart to input the secrets in base64 format, the "| b64enc" will convert the already inputed base64 value further into base64 and the jobs that my helm chart provision will fail. 

Hence, my request would be to provide any further alternative if possible.

**How to reproduce it** (as minimally and precisely as possible):
Try creating Kubernetes secrets using helm charts. 
In the values.yml, add placehloders for the secret , and publish your charts.
The set up ct using git workflows or any other way.
The ct tool picks up the placeholders and expects it to be in base64 format.

**Anything else we need to know**:
Attaching screenshot for reference
![helm-test-error](https://user-images.githubusercontent.com/41519748/91077789-51fc6b00-e65f-11ea-9cb8-977bd5ac4673.png)

**Comment by smlx** [comment]
`\u003e` is the unicode escape sequence for `>`, which is not a valid base64 character. This is a bug in your chart.

**Comment by ankitsrao** [comment]
Hi @smlx ,

Thank you for your inputs. But even after removing the <>, I get the same error.
Please find attached screenshot:
![helm-test](https://user-images.githubusercontent.com/41519748/91164473-b1ed2300-e6ec-11ea-883b-70aed95608ab.png)

**Comment by smlx** [comment]
You still have the same issue with your data: [this string](https://github.com/Cloudneeti/helm-charts/blob/master/charts/cloudneeti-agent/values.yaml#L19), even without the angle brackets, is not valid base64.

**Comment by ankitsrao** [comment]
@smlx , that is what my issue is. I have requested for any possible workaround.
Because I'm not hardcoding base64 secrets in my helm chart. I'll be taking it as an input from the user during the chart installation.

So as I already mentioned in my first comment:
One solution is that I can use the "| b64enc" for conversion in the chart itself, but then as I expect the user of the helm chart to input the secrets in base64 format, the "| b64enc" will convert the already inputed base64 value further into base64 and the jobs that my helm chart provisions will fail.

Hence, my request would be to provide any further alternative if possible.

Thanks,

**Comment by smlx** [comment]
Ah I see. The simplest option would be just to base64-encode your placeholder value.

**Comment by ankitsrao** [comment]
Yes, I tried that, even I have better solution, that I mentioned above, that I can use the "| b64enc" pipe in my values.yml. 
But since I want the end user to input secrets in base64 format, I can't use this solution.

Also, this suggestion would be for the sake of ct setup. So, I can't change the user experience just for the ct setup. Also, just putting a random base64 value as a placeholder would cause a bad cosmetic appearance of the chart.

Hence, if there could be any other way, using which this issue of base64 conversion of secrets could be bypassed is what I'm looking for.

Thanks,

**Comment by smlx** [comment]
Your issue has nothing to do with `chart-testing`. The fact is that the value you're inserting into the `data` field of the `Secret` isn't valid base64. Try installing the chart using the `values.yaml` I linked above and you'll get the same error.

**Comment by ankitsrao** [comment]
This means, there is no other option than to either update by placeholder values to random base64 strings, or either use the "| b64enc" pipe in my values.yml. is that correct?

**Comment by smlx** [comment]
No that's not the only solution.
Please review the documentation: https://kubernetes.io/docs/concepts/configuration/secret/
And also check how other charts configure secrets: https://github.com/helm/charts

**Comment by ankitsrao** [comment]
Hi @smlx ,

Thank you for the details.

I went through the charts and found that the "| b64enc" pipe has been used for the secrets, which I'm already aware of as mentioned.
The problem with this solution is that, the chart user needs to enter a plain-text secret value while installing the chart, which I feel is not a good security practice. The secrets should always be entered as a base64 value.

Also, I went through the lem doc, wheres it is suggesting to create secrets using the kubectl command. This defeats the whole purpose of my chart, which currently the one for all deployment strategy that I have in place.

So, the concern still prevails, is there any workaround for this base64 conversion during helm testing, as I want the user input to be secured in the first place.

Below is a link and screenshot of the chart I referred:
https://github.com/helm/charts/blob/master/incubator/azuremonitor-containers/templates/omsagent-secret.yaml
![helm-issue](https://user-images.githubusercontent.com/41519748/91550527-4b634180-e946-11ea-9990-8c74cb215054.png)

**Comment by smlx** [comment]
> The problem with this solution is that, the chart user needs to enter a plain-text secret value while installing the chart, which I feel is not a good security practice. The secrets should always be entered as a base64 value.

This is not correct. base64 has nothing to do with security. There is no security advantage to entering secrets already base64 encoded.

**Comment by unguiculus** [comment]
I'm closing this now. This is not related to chart-testing. Please check out the charts channel in Kubernetes Slack for general questions related to Helm charts. Thanks.
