### ISSUE TITLE
Identify unused Values

### ISSUE THREAD

**Issue by jrcasso** [helm/chart-testing#265]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature Request

**Version of Helm and Kubernetes**:

```
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.7"}
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-27T00:38:11Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
**What happened**:

Unused, deprecated Values went unnoticed without info/warning.

**What you expected to happen**:

`helm lint` should have an option to display a warning or info log for unused Values

**How to reproduce it** (as minimally and precisely as possible):

Run `helm lint` on a chart that establishes a key/value pair in `values.yaml` that goes unused.

**Comment by unguiculus** [comment]
Please post issues about Helm itself over at https://github.com/helm/helm. Thanks.
