### ISSUE TITLE
Support for validating users on Gitlab

### ISSUE THREAD

**Issue by foobaar** [helm/chart-testing#27]
It would be nice to validate user on Gitlab also. I love this feature, but for people using Gitlab, this feature might be limiting.

I can work on a PR for this, if you think this is a good idea.

**Comment by mattfarina** [comment]
We are open to a feature that does that.

**Comment by foobaar** [comment]
sounds, good I'll get a PR ready over this weekend.

**Comment by unguiculus** [comment]
Supported in v2.0.0
