### ISSUE TITLE
Need to compare local charts without being in a git repo

### ISSUE THREAD

**Issue by BenManifold** [helm/chart-testing#273]
**Is this a request for help?**:
Yes, if this is already possible.
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
- Ability to compare local chart directories without involving git.

**What happened**:
- I tried to execute 'ct list-changed --chart-dirs testChartNew/ testChartOld
- I was met with 'Error: Must be in a git repository', despite both charts being available locally with all necessary information at hand.

**What you expected to happen**:
- A comparison of the charts contained in those folders

**How to reproduce it** (as minimally and precisely as possible):
Create a fresh helm chart, copy it into two directories, make some trivial change to one of the charts. Attempt comparison.

**Anything else we need to know**:

**Comment by unguiculus** [comment]
There may be a misconception about what the tool does. chart-testing is not a diff tool that compares two directories. It is meant to be used with Git.
