### ISSUE TITLE
[BUG REPORT] ct list-changed  returns additional config as  output

### ISSUE THREAD

**Issue by chukka** [helm/chart-testing#276]
**Is this a request for help?**: **No**

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):**BUG**

```
ct version - 3.1.0

**What happened**:
Upgraded to CT - 3.1.0  on Mac and found that `ct list-changed` gives `Using config file: test/ct.yaml` in the output as first result
```
$ ct list-changed --config test/ct.yaml
Using config file: test/ct.yaml
stable/artifactory-ha
stable/artifactory

**What you expected to happen**: Expected output
$ ct list-changed --config test/ct.yaml
stable/artifactory-ha
stable/artifactory

**How to reproduce it** (as minimally and precisely as possible):
Use CT- 3.1.0 , change a chart locally and run `ct list-changed --config test/ct.yaml` using a config file it gives additional result of 
Using config file: test/ct.yaml
**Anything else we need to know**:

**Comment by chukka** [comment]
@unguiculus @davidkarlsen  Looks like a regression issue ?

**Comment by unguiculus** [comment]
Indeed, that's a regression. Sorry about that. Fix is on its way.
