### ISSUE TITLE
How to pass bash array env vars

### ISSUE THREAD

**Issue by hoesler** [helm/chart-testing#3]
> Note that CHART_DIRS, EXCLUDED_CHARTS, and CHART_REPOS must be configured as Bash arrays.

I cannot figure out, how to make a bash array env var accessible by the script. From what I read [here](https://unix.stackexchange.com/questions/353235/work-around-to-storing-array-values-in-an-environment-variable-then-calling-from) for example, this doesn't seem to be possible. This little example supports this assumption:

```
bash-4.4# export CHART_REPOS=("a=http://foo:8080" "b=http://bar.com:8080")
bash-4.4# echo "${CHART_REPOS[*]}"
a=http://foo:8080 b=http://bar.com:8080
bash-4.4# bash -c 'echo "${CHART_REPOS[*]}"'

bash-4.4#
```

**Comment by unguiculus** [comment]
I'll try and see if I can find a solution for this. In the meantime, I'd suggest you create a config file instead of using environment variables and source it. Have a look at https://github.com/kubernetes-helm/chart-testing/blob/master/chart_test.sh for reference.

**Comment by nvtkaszpir** [comment]
AFAIR the only way to export arrays in bash is to use separate file and then importing that file in subshell.

**Comment by philoserf** [comment]
Should this close as #35 (go rewrite) has been merged?

**Comment by hoesler** [comment]
I am fine with that.
