### ISSUE TITLE
Use of a Unix Pipeline in additional-commands

### ISSUE THREAD

**Issue by Preisschild** [helm/chart-testing#302]
**Is this a request for help?**:

no

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

I want to be able use a unix-pipeline in an additional-command, so i can template the charts and pass the yaml to another tool, like this
```yaml
additional-commands:
  - helm template ct-lint {{ .Path }} | kubeval
```
**Version of Helm and Kubernetes**:

ct: 
```
Version:         v3.3.0
Git commit:      2a4dfd420d066f821b39724fba89133f930a9953
Date:            2020-11-03T19:17:14Z
License:         Apache 2.0
```

helm:
```
version.BuildInfo{Version:"v3.4.0", GitCommit:"", GitTreeState:"", GoVersion:"go1.15.4"}
```
**What happened**:
`helm template`s  generated Yaml gets printed, but not passed to `kubeval` 

**What you expected to happen**:
kubeval output

**How to reproduce it** (as minimally and precisely as possible):
install helm, kubeval and ct
configure additional-commands in ct yaml like this: 
```yaml
additional-commands:
  - helm template ct-lint {{ .Path }} | kubeval
```

and execute `ct lint`

**Comment by Preisschild** [comment]
The problematic line appears to be in the [`RunCommand` function](https://github.com/helm/chart-testing/blob/9347b27afe57787f0e0cda01363a595b567db890/pkg/tool/cmdexecutor.go#L36). Only the first word gets executed as `cmd` and the rest as `arg`

**Comment by smlx** [comment]
Have you tried using a shell?
```
sh -c "helm template ct-lint {{ .Path }} | kubeval"
```

**Comment by Preisschild** [comment]
That seems to work, thanks for the
