### ISSUE TITLE
FEATURE REQUEST: Pass specific helm release name

### ISSUE THREAD

**Issue by smark88** [helm/chart-testing#310]
typical helm command: `helm install [NAME] [CHART] [flags]`

ct seems to use `--generate-name` I search issues and docs but maybe I missed but it'd be nice to have the ability to set the release name.

**Comment by gionn** [comment]
would be cool, right now I have some troubles during testing of a chart that depends on another chart that render a service and a secret and I don't have a way to know their name beforehand in order to have them set in the main chart values.
