### ISSUE TITLE
v2 fails to run helm init because helm stable repository has moved

### ISSUE THREAD

**Issue by fdlk** [helm/chart-testing#316]
**Version of Helm and Kubernetes**:
Using latest v2 docker image `quay.io/helmpack/chart-testing:v2.4.0`

**What happened**:
Run `helm init --client-only`.

```
+ helm init --client-only
Creating /root/.helm 
Creating /root/.helm/repository 
Creating /root/.helm/repository/cache 
Creating /root/.helm/repository/local 
Creating /root/.helm/plugins 
Creating /root/.helm/starters 
Creating /root/.helm/cache/archive 
Creating /root/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 

Error: error initializing: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden
```

**What you expected to happen**:
It works

**How to reproduce it** (as minimally and precisely as possible):
`docker run -it quay.io/helmpack/chart-testing:v2.4.0 helm init --client-only`

**Anything else we need to know**:
Upgrading the image to include helm v2.17.0 should fix this, see
https://helm.sh/blog/new-location-stable-incubator-charts/

**Comment by fdlk** [comment]
As a workaround, you can override the obsolete default using `--stable-repo-url https://charts.helm.sh/stable`

**Comment by jenting** [comment]
> As a workaround, you can override the obsolete default using `--stable-repo-url https://charts.helm.sh/stable`

For the people who had encountered it also, you could add below to your `ct.yaml`
```
chart-repos:
  - stable=https://charts.helm.sh/stable
```

**Comment by cpanato** [comment]
closing this, we dont do support for v2 anymore
but the solution is described above
