### ISSUE TITLE
FEATURE REQUEST - specify value files for linting

### ISSUE THREAD

**Issue by jdomag** [helm/chart-testing#327]
We have lot of helm charts with multiple values files. Would be great to be able specify a dir where those values are to change a default `./ct/*` dir, so people don't need to adjust their structure to use chart-testing.
Or even better and `--values` flag to be able to specify multiple value files for linting.

**Comment by carlosjgp** [comment]
Does this help?
https://github.com/helm/chart-testing/blob/ba5aed29ec88e9fc187915f115890cb174999a3c/ct/cmd/install.go#L46

otherwise, you can add the files through
https://github.com/helm/chart-testing/blob/ba5aed29ec88e9fc187915f115890cb174999a3c/ct/cmd/install.go#L64

and pass the `-f` flag there

**Comment by jdomag** [comment]
thanks, helm-extra-args does a trick!
