### ISSUE TITLE
OCI support?

### ISSUE THREAD

**Issue by szymonpk** [helm/chart-testing#331]
**This is a FEATURE REQUEST?**:

Would it be possible to add OCI repo support for the ct? It is enabled in Helm with proper env variable (`HELM_EXPERIMENTAL_OCI=1`), [link to the doc](https://helm.sh/docs/topics/registries/).

**Version of Helm and Kubernetes**:

```
$ helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.10", GitCommit:"98d5dc5d36d34a7ee13368a7893dcb400ec4e566", GitTreeState:"archive", BuildDate:"2021-04-23T12:04:36Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ ct version
Version:         v3.3.0
Git commit:      2a4dfd420d066f821b39724fba89133f930a9953
Date:            2020-11-03T19:17:04Z
License:         Apache 2.0
```

**What happened**:

I have a chart with the following dependencies:

```
dependencies:
  - name: foo
    version: "0.1.0"
    repository: oci://registry.gitlab.com/foo
```

I am running `ct lint --chart-dirs . --charts bar --validate-maintainers=false`, and I am getting an error:

```
Error: no repository definition for oci://registry.gitlab.com/foo. Please add the missing repos via 'helm repo add'
```

**What you expected to happen**:

ct lint running without an error.

**How to reproduce it** (as minimally and precisely as possible):

Create a chart and push to OCI registry like described here https://medium.com/@msvechla/distributing-helm-charts-via-gitlab-container-registry-a87ed2893647. And then use it as a dependency for other chart.

**Anything else we need to know**:

n/a

**Comment by jeff-cook** [comment]
I just ran into this myself.

Helm does support using an OCI registry for helm chart dependencies.
https://helm.sh/docs/topics/registries/#specifying-dependencies 

I can't find a way to `helm repo add` with an OCI registry.

**Comment by szymonpk** [comment]
Looks like it isn't an issue with chart-testing. It works with the latest Helm v3.6.0, [oci support was missing for 'dep`](https://github.com/helm/helm/commit/1135392b482f26f244c3c69f51511a1d82590eb7). Thanks @mattfarina! ;-)
