### ISSUE TITLE
Log output for container in 'ct install' does not terminate

### ISSUE THREAD

**Issue by pathob** [helm/chart-testing#332]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Version of Helm and Kubernetes**:

```
$ helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"archive", BuildDate:"2020-07-28T00:00:00Z", GoVersion:"go1.15rc1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"f00bd5fc5d1b9001e612847aa77f4e9c66758075", GitTreeState:"clean", BuildDate:"2021-03-22T23:03:44Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
$ ct version
Version:	 v3.3.1
Git commit:	 71d0e1e82c5c8b66ce4d9704426dc13b7075829d
Date:		 2020-11-30T20:10:04Z
License:	 Apache 2.0
```

**What happened**:

When running `ct install ...` the installation and tests do not terminate. The execution of ct gets stuck after:

```
<== Logs of init container crowd-uinddlbjpw-0
------------------------------------------------------------------------------------------------------------------------
>>> kubectl get pods crowd-uinddlbjpw-0 --no-headers --namespace crowd-uinddlbjpw --output jsonpath={.spec.containers[*].name}
------------------------------------------------------------------------------------------------------------------------
==> Logs of container crowd-uinddlbjpw-0
------------------------------------------------------------------------------------------------------------------------
>>> kubectl logs crowd-uinddlbjpw-0 --namespace crowd-uinddlbjpw --container crowd
```

The pod reaches running state and the displayed log is okay. But it just gets stuck there.

**What you expected to happen**:

As the installation (there are no actual tests yet) was successful, ct should just terminate successfully too.

If I copy the command for printing the logs from the ct output (`kubectl logs crowd-uinddlbjpw-0 --namespace crowd-uinddlbjpw --container crowd`) and execute it manually, the log output also terminates as expected.

**How to reproduce it** (as minimally and precisely as possible):

Unfortunately, the repo is currently private. If required, I can try to build a minimal version of that case.

**Anything else we need to know**:

I noticed this behavior in automated tests in Kind first. Manual executions in Azure (AKS) show the same behavior.

**Comment by pathob** [comment]
Problem still exists with chart-testing v3.4.0.

**Comment by ctron** [comment]
I am running into the same issue. With `helm/chart-testing-action@v2.1.0` and `v3.4.0` of chart testing.

**Comment by ctron** [comment]
> Not that I know and this project here seems quite abandoned... Does not even feels like worth the effort to debug the chart-testing code if PR's are not accepted anymore...

I noticed that too. Can you recommend any alternative?

**Comment by pathob** [comment]
I just had another look into the issue. The issue for me happens when a very long line from the kubectl log should be printed. The line generated by the Docker image in my case is almost 80000 characters long. It looks like ct cannot handle that while kubectl does not have any issue with that.
