### ISSUE TITLE
Support chart installation to an existing namespace

### ISSUE THREAD

**Issue by jlegrone** [helm/chart-testing#34]
I am working with an organization that runs a dedicated tiller instance for each set of namespaces owned by a given business unit. None of these tiller instances have cluster-admin permissions, nor can they create/delete arbitrary namespaces. Teams may also maintain their own chart repositories.

Specifying an existing namespace for chart installation would allow teams to consume this library in a more distributed and self-service manner, without the need for a dedicated cluster or access to a more highly privileged tiller instance.

**Comment by unguiculus** [comment]
The tool purposely installs charts into newly created namespaces that are deleted afterwards. If you don't want this why don't you just `helm install` the chart directly?

**Comment by jlegrone** [comment]
@unguiculus that's what I'm doing right now, however that means that I'm also separately implementing functionality around git diffs and picking up on values files in the `ci` subdirectory.

I realize that chart-testing originated just to suit the requirements of helm/charts, but enabling the use of namespaced privileges as described here would allow many more teams to leverage the library.

**Comment by jlegrone** [comment]
Ah, I do see now that `chartlib::print_pod_details_and_logs` just looks for all pods in the target namespace, so this would be a bigger change than I initially thought. If this feature request is approved, I could take a look at implementing this after the golang rewrite is merged.

**Comment by sonnysideup** [comment]
v2.0.0 is all written in Go. 😄

**Comment by jlegrone** [comment]
Now that `ct` is `go get`-able another use case this would help support is local invocation of chart tests by unprivileged users.

**Comment by mattfarina** [comment]
@unguiculus If I understand what you're saying, it's that someone who needs to install in an existing namespace should create a script that...

1. Installs and waits for all the things to come up
2. Run helm test on it
3. If they use `ci` values implement that
4. Deal with the results

I know we have some lessons learned from these that others may not have, too. For example, the way we wait for deployments in addition to helm waiting.

Would it be better to implement it here, for someone else to come up with a tool that does it, or others to do it as they need?
