### ISSUE TITLE
FEATURE REQUEST: Support parallel CT tests

### ISSUE THREAD

**Issue by chukka** [helm/chart-testing#352]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:  ct version : 3.4.0

**What happened**:
We are trying to see if parallel ct tests can be  run , As I understand each test runs on its own namespace. I think it makes sense to have parallel running support . 

For example : we have 5 to 10 tests under `ci` directory of each  product, It takes around 1 hour 30 mins (install + upgrade tests). we would like to improve the same by running them in parallel  to reduce time 

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by chukka** [comment]
@davidkarlsen @unguiculus please review

**Comment by rimusz** [comment]
Yes, an optional support for parallel runs for tests from the `ci` folder would really speed up testing of the chart changes

**Comment by joejulian** [comment]
How would you test charts that have ClusterRoles and Bindings, Webhooks, StorageClasses, etc - non-namespaced resources?

**Comment by chukka** [comment]
> How would you test charts that have ClusterRoles and Bindings, Webhooks, StorageClasses, etc - non-namespaced resources?
using vcluster ? we have been using vcluster along with [kuttl](https://github.com/kudobuilder/kuttl)  to support this feature 

cc @rimusz
