### ISSUE TITLE
Add filenames and line numbers to lint output

### ISSUE THREAD

**Issue by paddatrapper** [helm/chart-testing#367]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

The current `ct lint` output makes it difficult to match the detected issue with where in the templates it is found. Having file names and line numbers for where the issue is detected would make solving them much easier. For example, currently indentation issues are reported as 
```
 Error: [indentation] wrong indentation: expected 3 but found 2
```

Having an extra `at filename.yaml, Line #4` would make it easier to find and fix.

**Version of Helm and Kubernetes**: 

helm - 3.4.0

chart-testing - GitHub Action @ v2.1.0

**Comment by james-d-elliott** [comment]
Related: #282

**Comment by dimitarvdimitrov** [comment]
not adding value, but understanding this error when the change is more than a handful of lines is practically impossible
