### ISSUE TITLE
Ability to add '--skip-refresh' to "helm dependency build"

### ISSUE THREAD

**Issue by cep21** [helm/chart-testing#368]
**FEATURE REQUEST**

**What happened**:

When running chart-testing against multiple charts, the command `helm dependency build X` is run for each chart.  On each run, I see the following text
```
Hang tight while we grab the latest from your chart repositories...
```

We have many helm chart repositories and this refresh on each chart we test in our mono repo is the slowest part of our CI/CD since it involves external network calls.  Helm has an option, `--skip-refresh`, that can be passed to `dependency build`.  This will skip this refresh step and greatly speed up CI/CD in helm mono repo setups.

**What you expected to happen**:

An option to tell chart-testing to run the helm refresh once, at the start of the command, then run with --skip-refresh on each sub chart.  This will make CI/CD fast by not running refresh on each chart, but only at the start.

**How to reproduce it** (as minimally and precisely as possible):

Run chart-testing against multiple charts at once.

**Comment by nazarewk** [comment]
I'd love to see this feature too, this is the culprit: http://github.com/helm/chart-testing/blob/0a093e464b884565148eb71dda6999de0c956b17/pkg/tool/helm.go#L39-L41
