### ISSUE TITLE
Add option to `template` or `snapshot` test chart output

### ISSUE THREAD

**Issue by colearendt** [helm/chart-testing#370]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**: 

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

The SSO session associated with this profile has expired or is otherwise invalid. To refresh this SSO session run aws sso login with the corresponding profile.
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T03:27:49Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Unable to connect to the server: getting credentials: exec: executable aws failed with exit code 255
Version:	 3.3.1
Git commit:	 71d0e1e82c5c8b66ce4d9704426dc13b7075829d
Date:		 2020-11-30
License:	 Apache 2.0
```

**What happened**: For management of our helm charts, we are looking into setting up "snaphost" testing of our `ci/` directory values files. That is, we will `helm template` the output to a given file, and ensure that the output is up to date before merging any branch / changes. This will allow us to see the practical effects of our changes via a GitHub diff.

**What you expected to happen**: It would be nice if `ct` had a `template` or `snapshot` command that targets a particular directory and prints out the template output that is run through `ct lint`. Snapshot testing seems like a valuable option for "testing" helm charts, because the outcomes (in whitespace or otherwise) are often challenging to reason about.

Bonus points if there is a way to make "randomly generated values" stable or filter them out of the output... but that seems like it would be tricky / challenging / not worth it to do 😄 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by czomo** [comment]
Hey, have you tried to use ct with additional flags `--dry-run --debug` instead? Reference https://helm.sh/docs/chart_template_guide/debugging/

**Comment by colearendt** [comment]
I have not. It sounds like that may do the job of outputting the templates, but the other important parts of this process that I was hoping `ct` might wrap / do are:
- generate the template output
- write template output to a particular location (manually? say if you ran `--regenerate` or something)
- diff against existing files / fail testing if they differ (i.e. require regeneration)
- ignore parts of the template output that are time-sensitive so that it is idempotent (timestamps, use a consistent namespace, etc.)

**Comment by colearendt** [comment]
One pain point I have hit in hacky workarounds to this end is that the helm chart version number makes every release look like a change (and makes PRs bloat pretty seriously). I am planning to write a regex that strips out the version number and replaces with something like `VERSION` so we don't get the false changes.

The other thing is that some templating is non-deterministic in order (i.e. iterating over a map), so that can cause flaky snapshots too.
