### ISSUE TITLE
TODO: Push releases to registries

### ISSUE THREAD

**Issue by mattfarina** [helm/chart-testing#4]
We should push releases to docker hub, quay, and gcr (closer to our testing setup)

**Comment by unguiculus** [comment]
I'd suggest we also automate this.

**Comment by yatzek** [comment]
Can I suggest not to include the ci folder with *-values.yaml files in the published chart? There can be some sensitive data that should not be published with the chart.

**Comment by mattfarina** [comment]
@yatzek Two things:

* This should be filed as a separate issue. This one is about publishing the container image so others can easily pull it. Can you file that issue so that you can easily track it?
* This might be good as a configurable option because you are right that there are times this should not be included.

**Comment by yatzek** [comment]
Yes, your are right, raised #6

**Comment by mattfarina** [comment]
Now that releases go to Quay, I think we can close this
