### ISSUE TITLE
Decide on and document supported versions

### ISSUE THREAD

**Issue by scottrigby** [helm/chart-testing#45]
Since #35 / #29 this tool has been rewritten in Go, and the `v2.y.z` releases as of [v2.0.0](https://github.com/helm/chart-testing/releases/tag/v2.0.0) are now built from `master`. However, we still plan to support users who will require more time to upgrade from `v1` to `v2` for a period of time.

- [x] Decide on support status types (active, security/bug fixes only, EOL, etc), supported version granularity (probably MAJOR versions only), and timeline for each
- [x] Document supported versions
- [x] Document upgrading from `< v2`
- [x] Ensure branches per version (assuming `release-v1` branch for the old version, and `master` for v2 for now)
- [x] Document process for contributing relative to versions (normally open PRs against `master` per usual, but for legacy support open v1 PRs against `release-v1` branch, etc)

**Comment by scottrigby** [comment]
Branch `release-v1` was created from https://github.com/helm/chart-testing/commit/8e23ec2d74d04a2c9f288b8a3cf60aedbc183e73.

**Comment by scottrigby** [comment]
I started a WIP PR #47. I was thinking we can discuss the ideas here, and specific changes needed there, but whatever works for everyone 😄 

The `v1` dates reflect what @mattfarina suggested (3 months support), though we may want to change the status types (maybe we want to change `Active support until` and `Security support until` to `Actively maintained until` and `Security/bug fixes until`… etc). I also kept the `v2` dates as `?` because we haven't agreed on this timeline yet.

In general, I think that PR addresses the 3 open checkboxes above. What does everyone else think? Do we have more to-do items? Should we handle these ones differently?

**Comment by scottrigby** [comment]
Summary chat with @unguiculus:

- We can just state that we offer support for three months for the previous major release (release dates are listed already)
- No need to distinguish between security support and active support, so I'll just remove the whole table

**Comment by rimusz** [comment]
sounds good to me 👍

**Comment by scottrigby** [comment]
OK, I simplified it a lot more. Hopefully this makes the README easier to maintain.

One other note on branch naming, IMO it’s best to be explicit (rather than just a generic `support` branch, because that would get confusing if we ever make a new MAJOR release).

**Comment by scottrigby** [comment]
Fixed in #45
