### ISSUE TITLE
Error validating maintainer 'moritzschmitz-oviva': 429 Too Many Requests

### ISSUE THREAD

**Issue by moritzschmitz-oviva** [helm/chart-testing#455]
**Is this a request for help?**:

No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG_REPORT

**Version of Helm and Kubernetes**:

```
helm: version.BuildInfo{Version:"v3.9.1", GitCommit:"a7c043acb5ff905c261cfdc923a35776ba5e66e4", GitTreeState:"clean", GoVersion:"go1.18.4"}
kubectl: Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:21:56Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"darwin/arm64"}
ct: Version: 3.6.0
```

**What happened**:

When linting a lot of charts with maintainers at some point GitHub will throw a 429 and block requests.

**What you expected to happen**:

Do not spam the GitHub API. Either cache requests locally or respect rate-limits.

**How to reproduce it** (as minimally and precisely as possible):

Have a high number of charts to lint with every chart having the same and only maintainer.

**Anything else we need to know**:

Don't think so.

**Comment by davidkarlsen** [comment]
Looking at the code https://github.com/helm/chart-testing/blob/ba5aed29ec88e9fc187915f115890cb174999a3c/pkg/tool/account.go#L34 we could maybe benefit from using this api: https://github.com/google/go-github with caching: https://github.com/google/go-github#conditional-requests
