### ISSUE TITLE
ct failing with seemingly ok chart installation

### ISSUE THREAD

**Issue by knelasevero** [helm/chart-testing#458]
**Is this a request for help?**: 

yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

I am not sure. Might be a bug or miss-configuration. But better logging when we have errors is welcomed here. 

**Version of Helm and Kubernetes**:

setup helm action 2.1, helm 3.4.2, Kubernetes v1.24, chart-testing-action v2.2.1. You can check other versions at https://github.com/knelasevero/descheduler/blob/master/.github/workflows/helm.yaml

**What happened**:

Been getting `Error: Error installing charts: Error processing charts` errors with no other messages and I couldn't figure it out. 

Here is an example run: https://github.com/knelasevero/descheduler/runs/7567488579?check_suite_focus=true

In the events everything seems to be scheduled correctly with no problems. In the describe, same thing, all seems fine. In the logs the pod runs into one descheduler cycle with no problems as well.

But I just get `Error: Error installing charts: Error processing charts` + `descheduler => (version: "0.24.1", path: "charts/descheduler") > Error waiting for process: exit status 1`

**What you expected to happen**:

Chart to be installed and validated with no errors since I don`t get any errors from events/describe/logs and all seems fine.

**How to reproduce it** (as minimally and precisely as possible):

Can be checked in the public repo. https://github.com/knelasevero/descheduler/tree/master/.github/workflows

**Anything else we need to know**:

What I have tried so far:

- I had to change kind to be multi node for my specific use case, because descheduler will need more than one node to get into eviction cycle.
- I tried adding sleeps or just increasing the --wait of kind create to get a readier cluster for ct install
- Tried explicitly setting --chart-dirs charts, --config=.github/ci/ct.yaml, etc
-

**Comment by cpanato** [comment]
this is not related to the chart testing :)
discussed via twitter :)
closing
