### ISSUE TITLE
Composing multiple values files

### ISSUE THREAD

**Issue by scrungus** [helm/chart-testing#499]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request 

I'm asking this as I'm not sure what is the best way to go about this, or even if it is possible currently. 

Essentially, we have a repo that has some helm charts in it, which deploy onto a cloud via a credentials file we supply. 
So, we have a defaults `values.yaml` in each of the chart directories, and then a `ci` folder with specific versions of kubernetes we want to test and other specific info. Additionally we have a `clouds.yaml` file which contains the information required to deploy on a specific cloud. We don't want to store this in plaintext in the repo, so we store it as a CI secret. 

If we were using the command line tool, we would be able to lint doing something like `helm lint -f ci-values.yml -f clouds.yml`, but as far as I can tell, it is not possible to include an additional values file (i.e. no way to merge multiple values files other than the defaults and `ci` file) using `ct lint`. Is there a workaround way to do this or will it be added as a feature?

**Comment by scrungus** [comment]
If anyone is interested, I've forked and created this feature [here](https://github.com/marketplace/actions/helm-chart-testing-extravalues-fork) in a new github action

**Comment by krokofant** [comment]
Doesn't just something like this work? Just supply it as extra arguments to ct, and it'll pass it on to helm. Use another values file.
```
--helm-extra-args "-f argo-config/qa-values.yaml"
```
