### ISSUE TITLE
helm upgrade uses `reuse-values` by default

### ISSUE THREAD

**Issue by joejulian** [helm/chart-testing#525]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

version.BuildInfo{Version:"v3.11.0", GitCommit:"472c5736ab01133de504a826bd9ee12cbe4e7904", GitTreeState:"clean", GoVersion:"go1.19.5"}

ct version 2.7.1

**What happened**:
Upgrade failed when adding a new subchart in the new version because the new default chart values are ignored when reuse-values is specified. This caused the overrides in the new parent chart's values to be omitted and the subcharts defaults were used instead. As those overrides are required for the subchart to be a subchart, this caused the upgrade to fail.

When testing without `reuse-values` the upgrade is performed correctly.

Since using that flag is not a commonly documented way of upgrading charts, it should not be the default.

**What you expected to happen**:

I expected the common `helm upgrade <release> <chart> --wait` to be executed.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by xDmitriev** [comment]
I faced the exactly same issue. When I added new items in values.yaml, `ct install --ubgrade` is failed all the time

**Comment by xDmitriev** [comment]
Guys, what is the historical reason for having `--reuse-values` hardcoded here?

https://github.com/helm/chart-testing/blob/b8ad35cb0f40f65a0005e5d6dab204db25f0767d/pkg/tool/helm.go#L74

**Comment by xDmitriev** [comment]
@joejulian Does the upgrade mode work in your case, if you remove `--reuse-values` flag? Asking because it does not work in my case, I tried my own and your images, and there is a `timed out waiting for the condition` during the chart upgrade. But in fact, all pods getting ready after the upgrade, for some reason helm does not see that.

**Comment by joejulian** [comment]
@xDmitriev Yes, it works great.

**Comment by xDmitriev** [comment]
> @xDmitriev Yes, it works great.

Could you please share your CLI arguments? Or is it just `ct install --upgrade` ?

**Comment by joejulian** [comment]
https://github.com/redpanda-data/helm-charts/blob/main/.github/workflows/pull_requests.yaml#L89

The config file is:
https://github.com/redpanda-data/helm-charts/blob/main/.github/ct.yaml

**Comment by TheChef23** [comment]
This issue should not be closed IMHO, the hard coding of the reuse values makes the upgrade testing workflow essentially use when trying to test helm charts. Because adding new default values in the Helm chart is fine but not support by this testing tool at the moment.
