### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by kfox1111** [helm/chart-testing#529]
Went to use:
[add skip-clean-up](https://github.com/helm/chart-testing/commit/f661af1260dd80e7eadee43f960388814ee51dbf)
Then realized it was added the day after the last release and no release since.

Any chance for an update?

**Comment by kfox1111** [comment]
Heh. Forgot I hit this, and then just tripped across it a second time. Any change of a new release?

**Comment by chris-sanders** [comment]
I need this as well, I have a failing install and wanted to upload artifacts and without this I can't. Is there any workaround or does this need to be landed as the only path forward?

**Comment by cpanato** [comment]
will review and plan a release

**Comment by kfox1111** [comment]
The new release is working well. Thank you! :)
