### ISSUE TITLE
Remove implicit dependence on extra tools/repos

### ISSUE THREAD

**Issue by munnerz** [helm/chart-testing#53]
Hey all 👋 

First of all, thanks very much for this project. We use the old bash version of this in cert-manager and it works well 😄 

The recent Go rewrite is great, and I'm keen to get this setup in our own environment again.

I wonder if there is any desire to remove the dependence on yamale/yamllint?

We're hoping to be able to run this without the need for Docker, so for the time being will need to configure our own build/test environment to grab the appropriate version of these tools.

Can these projects either be included in the Go binary release somehow, or otherwise can their functionality be absorbed into Go?

**Comment by unguiculus** [comment]
Hey @munnerz, great to hear you use it. 😄

I'm not aware of any alternatives in Go that could replace these tools. However, I guess we could add flags for disabling them.

**Comment by cpanato** [comment]
The flags will be set up in the CT_XXXX env flags? 
I would like to try out this one. @unguiculus can we define the scope?

thanks

**Comment by unguiculus** [comment]
@cpanato You just flags in `lint.go`. The user is then free to choose whether they want to use the cli flag, an env var, or a config file to configure it.

I would add two flags:
* `no-chart-schema-validation`
* `no-yaml-lint`

What do you think?
@munnerz
