### ISSUE TITLE
maintainer validation ignores config flag

### ISSUE THREAD

**Issue by hoesler** [helm/chart-testing#54]
The option `--validate-maintainers=false` is ignored by `ct lint`.

Seems like this code block 
https://github.com/helm/chart-testing/blob/f632cd508104393b068e7c527d7f3d9ed47b5108/pkg/chart/chart.go#L299
should be surrounded with `if t.config.ValidateMaintainers {}`

Version: v2.0.0

**Comment by sonnysideup** [comment]
@hoesler The change to fix this bug has been merged into master; you can close this issue now. Thanks for reporting it.

**Comment by hoesler** [comment]
Thanks!
