### ISSUE TITLE
Separate helm install and helm test extra-args flags.

### ISSUE THREAD

**Issue by benjdaun** [helm/chart-testing#540]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm: version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}

Kubectl: Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:11Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:35:11Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

ct version:
Version:         3.7.1
Git commit:      f261a2809ace1dee3e597397c644082638786c64
Date:            2022-09-27
License:         Apache 2.0

**What happened**:
My command:

```
ct install <Release-name> --helm-extra-args "--logs" \ 
--helm-dependency-extra-args "--skip-refresh" --charts <chart-path> --namespace <release-namespace>
```

fails with the error message:
```
Error: unknown flag: --logs
Error deleting Helm release: failed waiting for process: exit status 1
```

**What you expected to happen**:

The ct command uses the --logs flag with the helm test command to print logs from the test pods.

**How to reproduce it** (as minimally and precisely as possible):

Select a chart to install, and include a `--helm-extra-args "--logs"` in the `ct install` command.

**Anything else we need to know**:

This raises the question of whether the helm-extra-args flag would need to be handled differently, and whether a helm-global-extra-args flag should be considered.

Consideration should also be given to how the logs from the test pods should be split from the default logs that are produced by this command.

**Comment by petewall** [comment]
I'd love to see this improvement.

**Comment by paologallinaharbur** [comment]
The workaround I found was to use env vars, in this way Helm does not complain if for extra unknown flags.

Example:
```
HELM_LOGS=true ct...
```
