### ISSUE TITLE
New release that includes --github-groups

### ISSUE THREAD

**Issue by krokofant** [helm/chart-testing#572]
I tried to use `ct lint --github-groups` but a new release hasn't been made since mars, and the `--github-groups` flag isn't released. Could a new release be made?

**Comment by marcofranssen** [comment]
Also waiting for a release including this feature.

@cpanato any chance you can tag a release?

**Comment by cpanato** [comment]
released here https://github.com/helm/chart-testing/releases/tag/v3.9.0
