### ISSUE TITLE
[BUG] targetBranch needs remote

### ISSUE THREAD

**Issue by mateusoliveira43** [helm/chart-testing#577]
**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG

**Version of Helm and Kubernetes**:

ct version
```
Version:	 v3.9.0
Git commit:	 88cc7026481da7468e34a614b8ca4f0da42c063c
Date:		 2023-07-10T16:57:18Z
License:	 Apache 2.0
```

**What happened**:

With the add of [verify if targetBranch is present in git repo](https://github.com/helm/chart-testing/pull/511), ct lint fails with false positive of `failed linting charts: failed identifying charts to process: targetBranch 'master' does not exist`.

**What you expected to happen**:

ct run normally.

**How to reproduce it** (as minimally and precisely as possible):

You need to run ct targeting a remote not default, since [this command](https://github.com/helm/chart-testing/blob/main/pkg/tool/git.go#L79) does not use remote information.

Ex.: `ct lint --remote other --config ct.yaml --target-branch master --debug`

Also, a [CI run with this error](https://github.com/dora-metrics/pelorus/actions/runs/5522381369/jobs/10071880037).

**Note:** This is not fixed with passing target-branch as "remote/branch", as it fails the following check.

Another [CI run with the other error](https://github.com/dora-metrics/pelorus/actions/runs/5523215657/jobs/10073830299?pr=1031).

**Comment by jouve** [comment]
as a workaround, you can add the following
```yaml
before_script:
  - git branch "$target_branch" "origin/$target_branch"
```

**Comment by xinzhang-lotusflare** [comment]
You can checkout the target branch, then checkout back to original branch. It works for me.

**Comment by thjaeckle** [comment]
This was working with Chart Testing 3.8.0 - and for me is also broken (as in: updated to 3.9.0 without any changes and got the message `Error: targetBranch 'master' does not exist`) in 3.9.0.
