### ISSUE TITLE
helm lint doesn't support all HelmExtraArgs (especially --timeout)

### ISSUE THREAD

**Issue by tobybellwood** [helm/chart-testing#604]
**Version of Helm and Kubernetes**:
using on Github Action in github runner
helm/chart-testing-action: v2.6.0

helm version: Helm 3.13.1
kubectl version: v1.27.3
ct version: 3.10.0

**What happened**:
The latest version of helm/chart-testing-action (v2.6.0) included ct version 3.10.0 - which, as per https://github.com/helm/chart-testing/pull/552 now adds the `--helm-extra-args` to the helm lint command.  Unfortunately, helm lint doesn't support the same extraArgs as the other helm commands, so the step fails in CI if you have an unsupported command in there (such as --timeout 60m) 

**What you expected to happen**:
Commands that aren't available to a subcommand shouldn't be passed, or the failure should be silent. 

**How to reproduce it** (as minimally and precisely as possible):
Add a `--timeout 10m` helmExtraArg to a ct.yaml file, and then run a `ci lint` or `ci lint-and-install` using it as a config and see the error

```
Linting chart with values file "charts/lagoon-test/ci/linter-values.yaml"...

Error: unknown flag: --timeout
Error: failed linting and installing charts: failed processing charts
```

**Anything else we need to know**:
In order to work around it, I had to remove the extraArgs from the shared config and run separate ci lint and ci install commands
```
ct lint --config ./test-suite-run.ct.yaml
ct install --config ./test-suite-run.ct.yaml --helm-extra-args "--timeout 60m"
```

**Comment by cpanato** [comment]
there is a bug in the lint part, will push a fix
