### ISSUE TITLE
Public OCI repositories support?

### ISSUE THREAD

**Issue by dennybaa** [helm/chart-testing#617]
Hi,
helm  login is hardcoded if any oci repository is used. I believe this is a mistake and there should be a support for a public oci repo (for example can be ghcr.io, and docker registry too btw).
WDYT?

**Comment by dennybaa** [comment]
oops. false positive.

**Comment by KrisF-Midnight** [comment]
Hi @dennybaa , I'm having the same issue with a public oci. 
As you said, login is hardcoded. How did you get around it?

```
func (h Helm) AddRepo(name string, url string, extraArgs []string) error {
	const ociPrefix string = "oci://"

	if strings.HasPrefix(url, ociPrefix) {
		registryDomain := url[len(ociPrefix):]
		return h.exec.RunProcess("helm", "registry", "login", registryDomain, extraArgs)
	}

	return h.exec.RunProcess("helm", "repo", "add", name, url, extraArgs)
}
```

**Comment by adberger** [comment]
Same here, also interested in a solution.

**Comment by dennybaa** [comment]
Hello guys, I'm not really up to date with this stuff,

but it might be I've mitigated this behavior

https://github.com/bitdeps/helm-oci-charts-releaser/blob/main/cr.sh#L379-L388

for example this works for https://github.com/bitdepscharts/charts/blob/main/.github/workflows/release.yaml#L28-L33, but I can't be sure, since in deps I'm not using an OCI repo :)

https://github.com/bitdepscharts/charts/blob/main/.github/ct.yaml

**Comment by adberger** [comment]
@dennybaa Thanks for the quick reply.
Releasing with an OCI dependency works for me as well. But not the chart-testing, since it's a different project(?)

**Comment by dennybaa** [comment]
yep 100%, it's a different project.
