### ISSUE TITLE
[Feature Request] Add support for specifying multiple kubernetes versions and capabilities

### ISSUE THREAD

**Issue by cornfeedhobo** [helm/chart-testing#619]
As a chart developer, I sometimes need to support many different versions of kubernetes, which requires tracking which versions support which resources.

I would like an easy way to lint a chart against a matrix of kubernetes versions and custom capabilities.

With the current execution model, I think this is implicitly covered in `install` when helm queries the running cluster.

**Comment by cornfeedhobo** [comment]
comment :middle_finger:

**Comment by cpanato** [comment]
You can create a job to have a matrix for the k8s versions you want, and then each call will use the kind cluster for the specific k8s version you want.

I think this is the best approach.
will close this issue for now
