### ISSUE TITLE
cannot detect changes

### ISSUE THREAD

**Issue by cometta** [helm/chart-testing#633]
i'm using ct version `3.10.1`

on my local machine, i add foo: bar in deployment.yaml file, then run the command
`ct list-changed --target-branch main` , `ct lint --target-branch main` no changes detected.  can advice on this?

```
Linting charts...

------------------------------------------------------------------------------------------------------------------------
No chart changes detected.
------------------------------------------------------------------------------------------------------------------------
```

may i know if there are files changes in /templates/*yaml folder , it should detect it right?

**Comment by viccuad** [comment]
not stale.

**Comment by cpanato** [comment]
@cometta @viccuad i just tested locally using `https://github.com/falcosecurity/charts` and chart repo and made a change in `https://github.com/falcosecurity/charts/blob/master/charts/falco/templates/client-certs-secret.yaml` for example and then run: 

```
$ pwd
/Users/cpanato/code/src/github.com/falcosecurity/charts

$ ct list-changed --target-branch master
charts/falco
```

can do you have a repo that i can try to reproduce or can you describe better the issue you are facing

**Comment by ebuildy** [comment]
I see same behavior, when commit to main branch:

`ct list-changed --chart-dirs charts` returns nothing

https://gitlab.com/tdecaux/helm-charts/-/jobs/6884479202

<img width="571" alt="Capture d’écran, le 2024-05-18 à 08 37 02" src="https://github.com/helm/chart-testing/assets/1219817/47a998f4-9dae-4af9-8220-aa95ba69d9f2">

**Comment by wzooff** [comment]
Few settings might cause this behaviour.
```
      --chart-dirs strings        Directories containing Helm charts. May be specified multiple times
                                  or separate values with commas (default [charts])
      --since string              The Git reference used to identify changed charts (default "HEAD")
      --target-branch string      The name of the target branch used to identify changed charts (default "main")
```
> may i know if there are files changes in /templates/*yaml folder , it should detect it right?

@cometta try to set `--chart-dirs=.` if `templates` directory is in repo root.

@ebuildy when you are in `master` already, `ct` can't compare. Try to run `git diff HEAD` - will be no output. In that case, try to specify `--since=HEAD~1` to check changes in the latest commit in the branch.
