### ISSUE TITLE
Add option to git diff between last 2 local commits

### ISSUE THREAD

**Issue by monotek** [helm/chart-testing#64]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
helm version: 2.11
kubectl version: 1.11
ct version: 2.0.1

**What happened**:
Please add an option to git diff between the last 2 local commits instead between local and remote repo.

I'd like to use ct on a local git repo which was cloned from a remote and therefore hase same commit locally as on the remote. Unfortunately the change detection don't works in this case and i only can use --all to get my charts tested.

**What you expected to happen**:
An option is available to enable change detection to use a diff to HEAD~1 instead to the remote.

**How to reproduce it** (as minimally and precisely as possible):
* Checkout your repo from remote to a local directory
* run ct lint locally
* "No chart changes detected."

**Comment by unguiculus** [comment]
Coud your explain your workflow? Generally speaking, this tool is meant to test changes against a target branch before they are merged. In your case, the chart already seems to be on the target branch. Why is this? Can you elaborate?

**Comment by monotek** [comment]
I've pushed directly to master without using a pr but still wanted the pipline to do the tests...

**Comment by unguiculus** [comment]
I assume this is the repo: https://github.com/monotek/helm-charts

Give this is a repo that's supposed to be added to the hub, I'd say it would make sense to test charts before they make it to master.

**Comment by monotek** [comment]
Yes, of course. The repo was more or less a test to copy the old helm/stable repo workflow without the need to have own infrastructure. At the end i wanted to have the repo on Github pages (https://monotek.github.io/charts/index.yaml) and the upload to that repo should be triggered after succesful test in https://github.com/monotek/helm-charts.

**Comment by auhlig** [comment]
I agree that it would be quite useful to not only diff to `HEAD` but to a configurable commit passed via a flag:
Tested and valid helm charts live on the master branch and changes can only be done by opening a PR and ensuring the helm chart tests pass. 
After merging the PR I want to `git diff ..` with the previous commit `HEAD~1` to be able to detect the changes, test again and finally push the chart to a helm repository.

**Comment by kyschouv** [comment]
This would be useful. We were able to work around it by setting `target-branch` to `master^` if we detected that `HEAD` and `origin/master` (our remote and target branch) were the same commit hash (and that there were no diffs in the files).
