### ISSUE TITLE
linux/s390x binaries

### ISSUE THREAD

**Issue by regel** [helm/chart-testing#682]
FEATURE REQUEST:

helm is available for many architectures, including linux/s390x, however, linux/s390x binaries are missing in helm/chart-testing Releases.

adding linux/s390x support looks like a quick win; I will try to submit a PR in the coming days.

**Comment by cpanato** [comment]
will add the thread here as well https://github.com/kubernetes-sigs/kind/issues/3754

**Comment by cpanato** [comment]
In this case, this is not a huge deal, I think we can have it.
but making a note here, if that causes any issues in our current pipeline we will decline it
