### ISSUE TITLE
CheckVersionIncrement is always fasle

### ISSUE THREAD

**Issue by monotek** [helm/chart-testing#71]
**Is this a request for help?**:

No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm 2.12
Kubectl 1.12
ct 2.0.1

**What happened**:
Were using a CircleCi pipeline (https://github.com/zammad/helm/blob/master/.circleci/config.yml) mainly based on the example from this repo.

When the chart is linted it does not fail when the chart version is not raised. See: https://circleci.com/gh/zammad/helm/150

CheckVersionIncrement is set to false even if it should be true by default.
Also the explicit setting of "check-version-increment: true" in ct.yaml is ignored.

**What you expected to happen**:
* linting fails if version is not raised.

**How to reproduce it** (as minimally and precisely as possible):
Use config from: https://github.com/zammad/helm/blob/master/.circleci

**Comment by monotek** [comment]
OK, seems this is the cause: https://github.com/helm/chart-testing/pull/56

Imho its still a problem that setting "check-version-increment: true" explicitly is ignored.

At least an error message like "parameters can't be used together" would be nice.

**Comment by monotek** [comment]
I guess if i put the chart into a subdirectory (charts )it would work.
Is this wanted behaviour?

**Comment by unguiculus** [comment]
I don't think #53 is your problem. If you want to lint all charts no matter if they changed or not, it makes sense to have the version check disabled. But #73 could indeed fix the issue. Please try again. v2.1.0 was just released.

**Comment by unguiculus** [comment]
You should not set the `--charts` flag, which causes this. Also, `--chart-dirs` should point to the repo root in your case. This this config:

```yaml
helm-extra-args: --timeout 3600
chart-dirs: "."
```

**Comment by monotek** [comment]
Oh, this seems to work now.
I've seen errors like ". can't be found" before in the install step. 
Can't reproduce now. Closing...
