### ISSUE TITLE
Add ct option to install charts with multiple values file one at a time

### ISSUE THREAD

**Issue by darkowlzz** [helm/chart-testing#83]
**Is this a request for help?**:
No.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

While installing charts with values files, all the charts are installed at the same time in different namespaces. This results in a lot of resource usage. When there's not enough resource available, some chart deployments fail. It would be great to have an option to install the charts with values files one at a time.

In https://github.com/helm/chart-testing/blob/v2.1.0/pkg/chart/chart.go#L345-L372, all the charts are installed with values together and cleaned up at the very end. An option to install with values, wait for deployments and delete release before installing with the next values file would help when there's a limited resource.

Would be great to know if there's a workaround for this already. If not, I can submit a PR adding an option to add the above behavior.

**Comment by unguiculus** [comment]
The tool already does exactly what you want. Everything is done sequentially. There is no parallelism.

**Comment by unguiculus** [comment]
I agree that using defer in a loop is not exactly a good idea. Plus, it causes the cleanup to happen in reverse order. However, this should not cause any of the problems you mention, especially not about ports. I'll try and look into this.

**Comment by unguiculus** [comment]
Fixed in #86. Please test.

**Comment by darkowlzz** [comment]
That works! Thanks a lot.
A new helmpack/chart-testing container image release with this fix would be great.
