### ISSUE TITLE
kubectl rollout status seems to not be failing when pods error

### ISSUE THREAD

**Issue by prydonius** [helm/chart-testing#9]
We discovered this issue where the test succeeded but the WordPress pod never started up and errored out, but the CI succeeded and the change got merged: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/helm_charts/7101/pull-charts-e2e/12374/?log#log

This is the PR, we should be able to reproduce it with this chart and manually running `kubectl rollout status` https://github.com/helm/charts/pull/7101.

If `kubectl rollout status` is not designed to return a non-zero error when rollouts fail, we may want to grep for error and fail if we get one here: https://github.com/helm/chart-testing/blob/master/lib/chartlib.sh#L273-L305

**Comment by unguiculus** [comment]
Yeah, I guess we have to resort to grep. I wish `helm wait` wouldn't look at `maxUnavailable`. What's the reason for this logic?

https://github.com/helm/helm/blob/7cad59091a9451b2aa4f95aa882ea27e6b195f98/pkg/kube/wait.go

cc @mattfarina

**Comment by prydonius** [comment]
I remember discussing it before, I think @thomastaylor312 explained the reasoning behind it one before, but I can't remember what it was now.

**Comment by unguiculus** [comment]
Fixed in #10.

**Comment by thomastaylor312** [comment]
I believe it is a better indicator if a `Deployment` is ready because then the amount of ready pods is above the max unavailable limit. I still need to make some time to clean up all of the wait stuff. If there is a good reason to not use MaxUnavailable (and what you'd rather see instead), let me know and I can take that into account
