### ISSUE TITLE
changes to readme file without raising the chart version does not fail

### ISSUE THREAD

**Issue by monotek** [helm/chart-testing#93]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm 2.12.3
Kubernetes 1.11
CT: 2.1.0

**What happened**:
Linting a chart did not fail on version check when only the readme of the chart was changed.

**What you expected to happen**:
As "CheckVersionIncrement" was set to "true" i expect linting to fail when the readme file, which will by part of the tgz archive, is changed but the chart version is not raised. 

**How to reproduce it** (as minimally and precisely as possible):
* just change the readme
* ct lint

**Anything else we need to know**:
Pipeline where we saw this: https://circleci.com/gh/kiwigrid/helm-charts/636

**Comment by unguiculus** [comment]
I just tested this with `v2.2.0`. Works as expected. Could you test with this version?

**Comment by monotek** [comment]
sorry, my fault. 
the commit of my colleague was on master.

**Comment by monotek** [comment]
Hmm... It just happened again in v2.2.0: https://circleci.com/gh/kiwigrid/helm-charts/957

**Comment by monotek** [comment]
sorry, my bad again. 
there was a pipe involved...
